
apiVersion: batch/v1
kind: Job
metadata:
  name: cypress-tests
spec:
  template:
    spec:
      containers:
      - name: cypress
        image: 27081984/cypress-project:latest
      restartPolicy: Never
  backoffLimit: 0
